project_id = "tqcgbsnoiarnawnppwia"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[functions.auto-scheduler]
verify_jwt = false

[functions.check-replies]
verify_jwt = false

[functions.generate-auto-reply]
verify_jwt = false

[functions.threads-webhook]
verify_jwt = false

[functions.threads-auto-reply]
verify_jwt = false

[functions.test-auto-reply]
verify_jwt = false

[functions.test-ai-auto-reply]
verify_jwt = false

[functions.auto-post-generator]
verify_jwt = false

[functions.self-reply-processor]
verify_jwt = false

[functions.test-modified-features]
verify_jwt = false

[functions.process-unhandled-replies]
verify_jwt = false

[functions.comprehensive-auto-reply-test]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.test-auto-post-generate]
verify_jwt = true

[functions.detect-rate-limited-personas]
verify_jwt = false
