@SUPABASE_ANON_KEY={{$processEnv VITE_SUPABASE_ANON_KEY}}

POST https://tqcgbsnoiarnawnppwia.supabase.co/functions/v1/test-modified-features
Content-Type: application/json
Authorization: Bearer {{SUPABASE_ANON_KEY}}

{}