import React from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { AutoRepliesList } from '@/components/AutoContent/AutoRepliesList';
import { AutoPostsList } from '@/components/AutoContent/AutoPostsList';

const AutoGeneratedContent = () => {
  const navigate = useNavigate();

  return (
    <div className="max-w-6xl mx-auto p-6">
      <div className="flex items-center mb-6">
        <Button 
          variant="outline" 
          size="sm" 
          onClick={() => navigate('/')}
          className="mr-4"
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          戻る
        </Button>
        <h1 className="text-3xl font-bold">自動文章作成確認</h1>
      </div>
      
      <Tabs defaultValue="replies" className="w-full">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="replies">自動返信</TabsTrigger>
          <TabsTrigger value="posts">自動投稿</TabsTrigger>
        </TabsList>
        
        <TabsContent value="replies" className="mt-6">
          <AutoRepliesList />
        </TabsContent>
        
        <TabsContent value="posts" className="mt-6">
          <AutoPostsList />
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default AutoGeneratedContent;
